server:
  port: 8080

spring:
  application:
    name: campaign-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/campaign
    username: sa
    password: admin
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
