server:
  port: 8080

spring:
  application:
    name: campaign-service
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

ampq:
  hostname: ${RABBITMQ_SERVER:localhost}
  port: 5672
  exchange: "nts"
  queue: "campaign"

logging:
  level:
    com.nts: DEBUG