server:
  port: 8080
  servlet:
    context-path: /rest

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/campaign
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
