server:
    port: 8090

spring:
    application:
        name: customer-service
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:file:~/customer
        username: sa
        password: admin
        driver-class-name: org.h2.Driver


feign:
    hystrix:
        enabled: true
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000

hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
            isolation:
                strategy: "THREAD"
                thread:
                    timeoutInMilliseconds: "3000"

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
