server:
  port: 8100

spring:
  application:
    name: team-service
  data.mongodb:
    host: ${RABBITMQ_SERVER:localhost}
    port: 27017
    database: team

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

