server:
  port: 8110

spring:
  application:
    name: customer-campaign-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/customer-campaign
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

ampq:
  hostname: ${RABBITMQ_SERVER:localhost}
  port: 5672
  exchange: "nts"
  queueNew: "campaign-new"
  queueUpdated: "campaign-updated"
  queueDeleted: "campaign-deleted"

logging:
  level:
    com.nts: DEBUG